[package]
name = "markdown-commonmark"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
markdown-parser = { git = "https://github.com/traq-markdown-parser/core.git", rev = "fd5c12c919719ba771c62d12585f667d106bfc8d", version = "0.1.0" }
markdown-commonmark-contracts = { path = "../contracts" }
unicode-general-category = "0.6"
mdurl = "0.3"
idna = "0.3"
regex = "1"

[dev-dependencies]
serde_json = "1"
